export type Lang = "en" | "zh";

export const content = {
  en: {
    nav: {
      about: "About",
      projects: "Projects",
      life: "Life",
      contact: "Contact",
      logo: "Alan Shao",
      subtitle: "Data Science & Finance · Boston University",
    },
    hero: {
      greeting: "👋  Hi there! I'm Alan",
      subtitle: "Hongyao Shao",
      bio: "Data Science & Business student at Boston University. I work at the intersection of data, technology, and business.",
      viewWork: "View my work",
      resume: "Resume",
      getInTouch: "Get in touch",
    },
    about: {
      heading: "About",
      bio1: "I'm a third-year student at Boston University pursuing a B.S. in Data Science and a B.S.B.A. in Business Administration & Management with a Finance concentration. I'm passionate about turning data into insights and decisions, whether that's building ML pipelines, analyzing financial markets, or visualizing complex datasets.",
      bio2: "Technical Project Manager at BU Spark!, and previously an analyst in investment and Web3 contexts. I enjoy building side projects that sit at the edge of what I know.",
      bio3: "Outside of work, I'm a travel enthusiast always chasing the next destination, and a big football fan :) Visca Barça !",
      educationLabel: "Education",
      school: "Boston University",
      degree1: "B.S. Data Science",
      degree2: "B.S.B.A. Business Administration & Management Finance Concentration",
      expectedGrad: "Expected May 2027",
      researchLabel: "Research Interests",
      researchText: "Machine learning and large language models, with a particular interest in mechanistic interpretability, understanding the internal representations and circuits of neural networks, and LLM-driven content analysis in social contexts.",
      skillsLabel: "Skills",
    },
    projects: {
      highlightsHeading: "Project Highlights",
      viewAll: "View all →",
      allHeading: "Projects",
      back: "← Back",
      allProjectsBack: "← All projects",
      viewProject: "View project →",
      tryDemo: "Try the demo →",
      sortedChronologically: "Listed chronologically",
    },
    life: {
      sectionHeading: "Beyond the Screen",
      sectionDesc: "Life beyond the screen — travels, football, and everything in between.",
      takeLook: "Take a look →",
      pageHeading: "Beyond the Screen",
      pageBack: "← Back",
      travelHeading: "Travelling",
      travelSubtitle: "Places I've been",
      wip: "This page is still taking shape, more of life beyond the screen coming soon...",
      legendVisited: "Been to",
      legendWishlist: "Want to go",
      legendNotYet: "Not yet",
    },
    contact: {
      heading: "Contact",
      github: "GitHub",
      linkedin: "LinkedIn",
      email: "Email",
    },
  },
  zh: {
    nav: {
      about: "关于",
      projects: "项目",
      life: "生活",
      contact: "联系",
      logo: "邵泓耀",
      subtitle: "数据科学与金融 · 波士顿大学",
    },
    hero: {
      greeting: "👋  你好，我是邵泓耀",
      subtitle: "Alan",
      bio: "波士顿大学在读，数据科学与工商管理双学位。专注于数据、技术与商业决策的交叉领域。",
      viewWork: "查看我的项目",
      resume: "简历",
      getInTouch: "与我联系",
    },
    about: {
      heading: "关于我",
      bio1: "就读于波士顿大学，主修数据科学（理学学士）与工商管理（金融方向）。专注于以数据驱动决策，涵盖机器学习项目开发、金融市场分析与数据可视化等方向。",
      bio2: "现任 BU Spark! 技术项目经理，曾从事投资分析及 Web3 相关工作，持续探索数据与技术的交叉应用。",
      bio3: "工作之余热爱旅行，亦是一名忠实的足球爱好者 :) Visca Barça ！",
      educationLabel: "教育背景",
      school: "波士顿大学（Boston University）",
      degree1: "数据科学 理学学士",
      degree2: "工商管理学士，金融方向",
      expectedGrad: "预计 2027 年 5 月毕业",
      researchLabel: "研究方向",
      researchText: "研究兴趣集中于机器学习与大语言模型领域，尤其关注机理可解释性（mechanistic interpretability）——通过解析神经网络的内部表征与计算回路，揭示模型行为的底层机制。此外，亦关注大语言模型在社会情境中的内容分析与应用研究。",
      skillsLabel: "技术栈",
    },
    projects: {
      highlightsHeading: "精选项目",
      viewAll: "查看全部 →",
      allHeading: "全部项目",
      back: "← 返回",
      allProjectsBack: "← 项目列表",
      viewProject: "查看项目 →",
      tryDemo: "试用 Demo →",
      sortedChronologically: "按时间倒序排列",
    },
    life: {
      sectionHeading: "屏幕之外",
      sectionDesc: "生活不止于屏幕——旅行、足球，还有那些说不清道不明的事。",
      takeLook: "了解更多 →",
      pageHeading: "屏幕之外",
      pageBack: "← 返回",
      travelHeading: "走过的地方",
      travelSubtitle: "打卡记录",
      wip: "这个页面还在慢慢完善，更多故事即将上线……",
      legendVisited: "去过",
      legendWishlist: "想去",
      legendNotYet: "还没去",
    },
    contact: {
      heading: "联系我",
      github: "GitHub",
      linkedin: "领英",
      email: "邮箱",
    },
  },
} as const;
